name = "Exact Match - URL (/json)"
priority = 2

[request]
url = "/json"

[response]
body_file_name = "json-response.json"

[[response.headers]]
key = "Content-Type"
value = "application/json"

[[response.headers]]
key = "Accept"
value = "application/json"