name = "Exact Match - URL, Header (/json)"
priority = 1

[request]
url = "/json"

[request.header]
key = "X-Correlation-Id"
value = "not-found"

[response]
status = 404
body_file_name = "not-found.json"

[[response.headers]]
key = "Content-Type"
value = "application/json"

[[response.headers]]
key = "Accept"
value = "application/json"