name = "Pattern Match - Header (/header-pattern)"
priority = 1

[request]
url = "/header-pattern"

[request.header_pattern.key]
left = "X-Pattern-Match"

[request.header_pattern.value]
right = "^yoda.*"

[response]
body_file_name = "header-pattern-match-response.json"

[[response.headers]]
key = "Content-Type"
value = "application/json"

[[response.headers]]
key = "Accept"
value = "application/json"