name = "Pattern Match - URL (/weather/\\d{5}$)"
priority = 1

[request]
url_pattern = '/weather/\d{5}$'

[response]
body_file_name = "weather-response.json"

[[response.headers]]
key = "Content-Type"
value = "application/json"

[[response.headers]]
key = "Accept"
value = "application/json"