priority = 10

[request]
method = "GET"
url = "/mobilecheckout/healthcheck"

[response]
proxy-base-url = "http://jasonozias.com"

    [[response.additional-proxy-request-headers]]
    key = "User-Agent"
    value = "krogerco/13.0/iOS"