priority = 10

[request]
method = "GET"
url = "/mobilecheckout/healthcheck"

[response]
proxy_base_url = "http://www.espn.com"

[[response.additional_proxy_request_headers]]
key = "User-Agent"
value = "krogerco/13.0/iOS"