name = "Proxy - jasonozias.com"
priority = 10

[request]
method = "GET"
url = "/"

[response]
proxy_base_url = "https://jasonozias.com"

[[response.additional_proxy_request_headers]]
key = "User-Agent"
value = "krogerco/13.0/iOS"