priority = 1

[request]
url = "/json"

[response]
body_file_name = "json-response.json"

[[response.headers]]
key = "Content-Type"
value = "application/json"

[[response.headers]]
key = "Accept"
value = "application/json"